version: '3.0'
services:
  api:
    build: . 
    ports:     
      - "8081:80"    
    depends_on:      
      - db 
  db:
    image: mysql:5.7
    environment:
      TZ: "America/Brasilia"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: clients
      MYSQL_PORT: 3306
      MYSQL_HOST: 127.0.0.1
    ports:
      - "3306:3306"
    
